name = "AuditoryBistabilityLE"
uuid = "7e25a372-ade5-11e8-17af-a30e5a9e2c28"
authors = ["David Little <david.frank.little@gmail.com>"]
version = "0.6.1"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CorticalSpectralTemporalResponses = "82ec0db2-aa68-11e9-08e4-e3d69fc08b96"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
MetaArrays = "36b8f3f0-b776-11e8-061f-1f20094e1fc8"
NMF = "6ef6ca0d-6ad7-5ff6-b225-e928bfa0a386"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlotAxes = "8b6f5f00-d239-11e8-3a24-33314b00f6b0"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Rmath = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TOML = "191fdcea-f9f2-43e0-b922-d33f71e2abc3"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AxisArrays = ">=0.3.0"
Combinatorics = ">=0.7.0"
DSP = ">=0.5.1"
DataFrames = ">=0.15.0"
DataStructures = ">=0.14.0"
Distributions = ">=0.16.4"
MacroTools = ">=0.4.4"
Match = "1.0.1"
MetaArrays = ">=0.2.0"
NMF = ">=0.4.0"
Parameters = ">=0.10.1"
ProgressMeter = ">=0.6.0"
Requires = ">=0.5.2"
SpecialFunctions = ">=0.7.1"
StatsFuns = ">=0.7.0"
TOML = ">=0.4.0"
Unitful = ">=0.12.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
